[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 1

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 2

[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 3

[[main]]
  identifier = "contact"
  name = "Contact"
  url = "contact"
  weight = 4

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 5
