version: "2"

plugins:
  eslint:
    enabled: true
    channel: "eslint-5"
    config:
      config: .eslintrc.js

checks:
  method-complexity:
    enabled: false
  method-lines:
    config:
      threshold: 150
  similar-code:
    enabled: false
  identical-code:
    enabled: false

ratings:
  paths:
    - "**.js"
    - "**.scss"

exclude_paths:
  - public/*
  - .cache/*
  - cypress/*
  - src/assets/*
  - src/styles/helpers/_prism.scss
