dist: bionic
language: node_js

node_js:
  - '8'
  - '10'
  - '11'
  - '12'

before_install:
  - sudo apt-get update
  - sudo apt install -y libgconf-2-4

git:
  quiet: true

cache: yarn

script:
  - 'yarn test:e2e:ci'
  - 'yarn build'
