baseURL = "https://asjas.xyz/" # The URL of your site.
title = "A-J Roos" # Title of your site
theme = "zzo" # Name of Zzo theme folder in `themes/`.
languageCode = "en-us"

summaryLength = 70 # The length of a post description on a list page.

copyright = "©{year}, All Rights Reserved" # copyright symbol: $copy; current year: {year}
timeout = 10000
enableEmoji = true
paginate = 13 # Number of items per page in paginated lists.
rssLimit = 100

enableGitInfo = false # When true, the modified date will appear on a summary and single page. Since GitHub info needs to be fetched, this feature will slow down to build depending on a page number you have
googleAnalytics = ""
